"""add calculation history table

Revision ID: 1eee66ee8cd8
Revises: 76811b6fb244
Create Date: 2026-02-21 19:26:48.409520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1eee66ee8cd8'
down_revision: Union[str, Sequence[str], None] = '76811b6fb244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calculation_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('investment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calculation_history_id'), 'calculation_history', ['id'], unique=False)
    op.create_index(op.f('ix_calculation_history_user_id'), 'calculation_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calculation_history_user_id'), table_name='calculation_history')
    op.drop_index(op.f('ix_calculation_history_id'), table_name='calculation_history')
    op.drop_table('calculation_history')
    # ### end Alembic commands ###
